name: Pack and Push Action
description: Pack and Push a name, version and nuget source configuration
inputs:
  Top-Level-Source-Directory:
    description: 'Directory within which all desired project sub-directories are contained'
    requried: true
    default: './src/'
  Package-Name-Suffix:
    description: 'Nuget package name suffix to add to each project'
    required: true
    default: '-dev'
  Use-Name-Suffix:
    description: 'Whether to modify project names with suffix or not'
    required: true
    default: false
  Version-String:
    description: 'The version string to stamp on all projects'
    required: true
    default: '0.0.0.0'
  Nuget-Source:
    description: 'The nuget location to upload the package'
    required: true
    default: 'error'
  Nuget-Api-Key:
    description: 'The nuget api key for the package source location'
    required: true
    default: 'error'
runs:
  using: "composite"
  steps:
    - name: Run pack and push script for requested configuration
      run: sudo ${{ github.action_path }}packandpush.sh
      shell: bash
      env:
        TEST_VARIABLE_0: ${{ inputs.Package-Name-Suffix }}
        TEST_VARIABLE_1: ${{ inputs.Nuget-Api-Key }}
